# Generated by Django 3.2.4 on 2021-06-19 13:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210618_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('specialty', models.CharField(default='general', max_length=64)),
                ('city', models.CharField(max_length=16)),
                ('lga', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=16)),
                ('address', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('health_officer', models.ManyToManyField(to='api.HealthOfficer')),
                ('patients', models.ManyToManyField(to='api.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('test_category', models.CharField(default='Examine', max_length=256)),
                ('test_type', models.CharField(default='Blood Test', max_length=256)),
                ('test_result', models.TextField(default='')),
                ('prescription', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('health_officer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.healthofficer')),
                ('hospital', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hospital')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
    ]
